### ISSUE TITLE
Unable to get data from API / Version 1.0.3

### ISSUE THREAD

**Issue by crewo15** [p0l0/hagruenbeck_cloud#227]
## System Information

version | core-2025.7.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
container_arch | amd64
user | root
virtualenv | false
python_version | 3.13.3
os_name | Linux
os_version | 6.12.34-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/p0l0/hagruenbeck_cloud/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

HA 2025.7.1 / Version 1.0.3

After updating from 1.0.2 to 1.0.3 the integration is still not working, I've got this error message:

Unable to get data from API: 'NoneType' object has no attribute 'is_expired'

### Reproduction steps

N.n.

### Debug logs

```text
Logger: custom_components.gruenbeck_cloud.coordinator
Quelle: custom_components/gruenbeck_cloud/coordinator.py:192
Integration: Grünbeck Cloud

Unable to login
```

**Comment by crewo15** [comment]
@p0l0 If you need more information please let me know!

**Comment by markus321** [comment]
During my installation I get the following error message

Einrichtungsfehler, wird erneut versucht: Unable to get data from API: {0: {'description': ['Unknown field.']}, 1: {'description': ['Unknown field.']}, 2: {'description': ['Unknown field.']}, 3: {'description': ['Unknown field.']}, 4: {'description': ['Unknown field.']}}

**Comment by p0l0** [comment]
> @p0l0 If you need more information please let me know!

Which model do you have? For my SD it's working fine again.

**Comment by p0l0** [comment]
> During my installation I get the following error message
> 
> Einrichtungsfehler, wird erneut versucht: Unable to get data from API: {0: {'description': ['Unknown field.']}, 1: {'description': ['Unknown field.']}, 2: {'description': ['Unknown field.']}, 3: {'description': ['Unknown field.']}, 4: {'description': ['Unknown field.']}}

Are you using version 1.0.3? This error was fixed today with that version

**Comment by markus321** [comment]
> > During my installation I get the following error message
> > Einrichtungsfehler, wird erneut versucht: Unable to get data from API: {0: {'description': ['Unknown field.']}, 1: {'description': ['Unknown field.']}, 2: {'description': ['Unknown field.']}, 3: {'description': ['Unknown field.']}, 4: {'description': ['Unknown field.']}}
> 
> Are you using version 1.0.3? This error was fixed today with that version

I've now installed version 1.0.3. It's working again. Thanks for the update.

**Comment by crewo15** [comment]
@p0l0 Typ: softliQ:SD21, Software Version 0003.0040

**Comment by tibor62** [comment]
I deleted version 1.02 and reinstalled version 1.03. Unfortunately, the integration still does not work for me. I have the same problem. When I enter my login credentials, I receive the message 'an unexpected error' just like before with version 1.02.

**Comment by tibor62** [comment]
Today I reinstalled version 1.03 via HA. Unfortunately, the integration still does not work for me. I have the same problem. When I enter my login credentials, I receive the message "an unexpected error", just like before in version 1.02. 
Here is what the log looks like.
----------------------------------------------------
Logger: custom_components.gruenbeck_cloud.config_flow
Quelle: custom_components/gruenbeck_cloud/config_flow.py:48
Integration: Grünbeck Cloud (Dokumentation, Probleme)
Erstmals aufgetreten: 11:32:23 (6 Vorkommnisse)
Zuletzt protokolliert: 12:27:40

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gruenbeck_cloud/config_flow.py", line 48, in async_step_user
    self.devices = await self.get_devices(user_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gruenbeck_cloud/config_flow.py", line 127, in get_devices
    if not await api.login():
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 194, in login
    if not await self._login_step2(auth_data):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pygruenbeck_cloud/pygruenbeck_cloud.py", line 317, in _login_step2
    parsed_response = json.loads(response)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Schleek** [comment]
Working with version 1.0.4
Thanks to the developper

**Comment by crewo15** [comment]
Thank you, 1.0.4 works for me!
